# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '8.0'
target 'PubNubTest' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'PubNub', '~>4.0'
end
target 'PubNubTestTests' do
end